version: "3.8"
services:
  botany-web:
    build: .
    container_name: botany-web
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/botany-web/data:/home/botany/.botany
    restart: always
